# Generated by Django 3.2.16 on 2022-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned',
            field=models.BooleanField(default=False, verbose_name='Запалнировано'),
        ),
    ]
