# Generated by Django 3.2.10 on 2022-11-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task_planned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='planned',
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('todo', 'Сделать'), ('progress', 'В работе'), ('done', 'Закончена')], default='todo', max_length=20),
        ),
    ]
