# Generated by Django 3.2.10 on 2022-11-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_task_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='horizon',
            field=models.IntegerField(verbose_name='Горизонт'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('todo', 'Сделать'), ('progress', 'В работе'), ('done', 'Закончена'), ('inbox', 'Входящая'), ('removed', 'Удалена')], default='todo', max_length=20),
        ),
    ]
